# Default state for all rules
default: true

# Disable rules that conflict with Prettier
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Prettier.md
extends: markdownlint/style/prettier

# no-duplicate-heading
MD024:
  siblings_only: true
