extends: default

rules:
  # Let Prettier handle most formatting
  colons: disable
  commas: disable
  comments:
    min-spaces-from-content: 1 # Match Prettier formatting
  empty-lines: disable
  hyphens: disable
  indentation: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: disable # Let end-of-file-fixer handle formatting
  trailing-spaces: enable

  document-start: disable
  empty-values: enable
  octal-values: enable
